# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtn_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form_Students(object):
    def setupUi(self, Form_Students):
        Form_Students.setObjectName("Form_Students")
        Form_Students.resize(312, 278)
        self.label = QtWidgets.QLabel(Form_Students)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_Students)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_Students)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_Students)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_Students)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.label_5.setObjectName("label_5")
        self.textEditNombre = QtWidgets.QTextEdit(Form_Students)
        self.textEditNombre.setGeometry(QtCore.QRect(110, 20, 161, 21))
        self.textEditNombre.setObjectName("textEditNombre")
        self.textEditApellido = QtWidgets.QTextEdit(Form_Students)
        self.textEditApellido.setGeometry(QtCore.QRect(110, 50, 161, 21))
        self.textEditApellido.setObjectName("textEditApellido")
        self.textEditEstatura = QtWidgets.QTextEdit(Form_Students)
        self.textEditEstatura.setGeometry(QtCore.QRect(110, 110, 161, 21))
        self.textEditEstatura.setObjectName("textEditEstatura")
        self.textEditPeso = QtWidgets.QTextEdit(Form_Students)
        self.textEditPeso.setGeometry(QtCore.QRect(110, 140, 161, 21))
        self.textEditPeso.setObjectName("textEditPeso")
        self.dateEdit = QtWidgets.QDateEdit(Form_Students)
        self.dateEdit.setGeometry(QtCore.QRect(110, 170, 161, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButtonRegistrar = QtWidgets.QPushButton(Form_Students)
        self.pushButtonRegistrar.setGeometry(QtCore.QRect(20, 200, 75, 31))
        self.pushButtonRegistrar.setObjectName("pushButtonRegistrar")
        self.pushButtonPromedio = QtWidgets.QPushButton(Form_Students)
        self.pushButtonPromedio.setGeometry(QtCore.QRect(100, 200, 75, 31))
        self.pushButtonPromedio.setObjectName("pushButtonPromedio")
        self.pushButtonMedia = QtWidgets.QPushButton(Form_Students)
        self.pushButtonMedia.setGeometry(QtCore.QRect(180, 200, 75, 31))
        self.pushButtonMedia.setObjectName("pushButtonMedia")
        self.pushButtonModa = QtWidgets.QPushButton(Form_Students)
        self.pushButtonModa.setGeometry(QtCore.QRect(20, 230, 75, 31))
        self.pushButtonModa.setObjectName("pushButtonModa")
        self.pushButtonMinimo = QtWidgets.QPushButton(Form_Students)
        self.pushButtonMinimo.setGeometry(QtCore.QRect(100, 230, 75, 31))
        self.pushButtonMinimo.setObjectName("pushButtonMinimo")
        self.pushButtonMaximo = QtWidgets.QPushButton(Form_Students)
        self.pushButtonMaximo.setGeometry(QtCore.QRect(180, 230, 75, 31))
        self.pushButtonMaximo.setObjectName("pushButtonMaximo")
        self.textEditCedula = QtWidgets.QTextEdit(Form_Students)
        self.textEditCedula.setGeometry(QtCore.QRect(110, 80, 161, 21))
        self.textEditCedula.setObjectName("textEditCedula")
        self.label_6 = QtWidgets.QLabel(Form_Students)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form_Students)
        QtCore.QMetaObject.connectSlotsByName(Form_Students)

    def retranslateUi(self, Form_Students):
        _translate = QtCore.QCoreApplication.translate
        Form_Students.setWindowTitle(_translate("Form_Students", "Registro Estudiante"))
        self.label.setText(_translate("Form_Students", "Nombre"))
        self.label_2.setText(_translate("Form_Students", "Apellido"))
        self.label_3.setText(_translate("Form_Students", "Estatura"))
        self.label_4.setText(_translate("Form_Students", "Peso"))
        self.label_5.setText(_translate("Form_Students", "Nacimiento"))
        self.pushButtonRegistrar.setText(_translate("Form_Students", "Registrar"))
        self.pushButtonPromedio.setText(_translate("Form_Students", "Promedio"))
        self.pushButtonMedia.setText(_translate("Form_Students", "Media"))
        self.pushButtonModa.setText(_translate("Form_Students", "Moda"))
        self.pushButtonMinimo.setText(_translate("Form_Students", "Minimo"))
        self.pushButtonMaximo.setText(_translate("Form_Students", "Maximo"))
        self.label_6.setText(_translate("Form_Students", "Cedula"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Students = QtWidgets.QWidget()
    ui = Ui_Form_Students()
    ui.setupUi(Form_Students)
    Form_Students.show()
    sys.exit(app.exec_())
